### ISSUE TITLE
Package on PyPI and conda-forge

### ISSUE THREAD

**Issue by jfrost-mo** [Fraetor/simple_template#5]
A package for this module should be uploaded to PyPI and then conda-forge.

**Comment by jfrost-mo** [comment]
https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/

**Comment by jfrost-mo** [comment]
The release should be tagged `1.0`.

**Comment by jfrost-mo** [comment]
The release environment also needs to be setup.

**Comment by Fraetor** [comment]
Now packaged on PyPI. Conda-forge is in the works in https://github.com/conda-forge/staged-recipes/pull/25143
